// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEMRcz_Dx1LQPKQhHX5_DlLiBbMuPgX0',
    appId: '1:802250925697:web:dbb8ef576c51ccaaea0f80',
    messagingSenderId: '802250925697',
    projectId: 'voleyballtraining',
    authDomain: 'voleyballtraining.firebaseapp.com',
    storageBucket: 'voleyballtraining.firebasestorage.app',
    measurementId: 'G-5TJKZJTXRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHjxIXsH86bf5AeeBNvjJyApZ67lY1EyM',
    appId: '1:802250925697:android:b86f9f12da42985bea0f80',
    messagingSenderId: '802250925697',
    projectId: 'voleyballtraining',
    storageBucket: 'voleyballtraining.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkIdoUXWavh23CoK47p0oLy7SBmRLcO0s',
    appId: '1:802250925697:ios:d8f242078fe32329ea0f80',
    messagingSenderId: '802250925697',
    projectId: 'voleyballtraining',
    storageBucket: 'voleyballtraining.firebasestorage.app',
    iosBundleId: 'com.example.voleyballtraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkIdoUXWavh23CoK47p0oLy7SBmRLcO0s',
    appId: '1:802250925697:ios:d8f242078fe32329ea0f80',
    messagingSenderId: '802250925697',
    projectId: 'voleyballtraining',
    storageBucket: 'voleyballtraining.firebasestorage.app',
    iosBundleId: 'com.example.voleyballtraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpEMRcz_Dx1LQPKQhHX5_DlLiBbMuPgX0',
    appId: '1:802250925697:web:635c30eff1aab702ea0f80',
    messagingSenderId: '802250925697',
    projectId: 'voleyballtraining',
    authDomain: 'voleyballtraining.firebaseapp.com',
    storageBucket: 'voleyballtraining.firebasestorage.app',
    measurementId: 'G-0ZBW65KN0H',
  );
}
