name: voleyballtraining
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0 # Usa la última versión disponible
  # Firebase Authentication
  firebase_auth: ^4.20.0 # Usa la última versión disponible
  # Cloud Firestore
  cloud_firestore: ^4.17.5 # Usa la última versión disponible
  # State Management (Ejemplo con Provider)
  provider: ^6.1.2 # Usa la última versión disponible
  cupertino_icons: ^1.0.6 # Usa la última versión disponible
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/fondo.png
    - assets/images/hinata_container_default.png
    - assets/images/Logo-icon.png
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
